---
- hosts: localhost
  become: true
  become_user: root
  gather_facts: yes
  
  tasks:
  - name: deploy CFT
    cloudformation:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      stack_name: "awswest-deploy"
      state: "present"
      region: "{{ aws_region }}"
      disable_rollback: true
      template: "/root/.jenkins/workspace/aws-deploy/ansiblewest.yaml"
